Header set Cache-Control "max-age=604800, public"
AddType application/x-httpd-php .html .htm .json
ErrorDocument 404 /search/?q=404

RewriteEngine On

RewriteCond %{HTTP_HOST} ^www\.txwes\.edu$
RewriteRule ^(.*) https://txwes.edu/$1 [R=301]

RewriteCond %{HTTP_HOST} ^http://txwes\.edu$
RewriteRule ^(.*) https://txwes.edu/$1 [R=301]

RewriteCond %{HTTP_HOST} ^bbsupport\.txwes\.edu$
RewriteRule ^(.*) https://help.edusupportcenter.com/shplite/txwes/home [R=301]

RewriteRule ^Media/Website(\ |%20)Resources/(.+)$ http://txwes.edu/media/website-resources/$2 [R=301]

RewriteRule ^communications/resources/web-accessibility(.+)$ /communications/policies--procedures/web-accessibility$1 [R=301]
RewriteRule ^admissions/what-will-it-cost(.+)$ /admissions/financial-aid--scholarships$1 [R=301]

RewriteRule ^media/twu/content-assets/documents/communications/brand/Wesleyan_Athletics_QuickGuide.pdf$ /search/?q=404 [R=410]

RewriteRule ^art$ /art-gallery/ [R=301]
RewriteRule ^art/(.*)$ /art-gallery/$1 [R=301]

<t4 type="navigation" id="359"/>

RewriteRule ^admissions/my-award/exit-counseling(.*)$ /admissions/scholarships-and-aid/my-award/exit-counseling$1 [R=301]

RewriteRule ^admissions/meet-with-a-counselor/graduate-counselors/meet-teva(.*)$ /search/?q=404 [R=410]

RewriteRule ^academics/registrar/course-catalog(.*)$ https://catalog.txwes.edu/ [R=301]

RewriteRule ^fees-costs-and-policies/university-policies/privacy-policies(/)?$ /admissions/what-will-it-cost/fees-costs-and-policies/university-policies/privacy-policy/ [R=301]

RewriteRule ^online-mba-search(.*)$ /online-mba$1 [R=301]
RewriteRule ^online-mba-display(.*)$ /online-mba$1 [R=301]
RewriteRule ^online-mba-remarketing(.*)$ /online-mba$1 [R=301]

RewriteRule ^online-med-search(.*)$ /online-master-of-education$1 [R=301]
RewriteRule ^online-med-display(.*)$ /online-master-of-education$1 [R=301]
RewriteRule ^online-med-facebook(.*)$ /online-master-of-education$1 [R=301]
RewriteRule ^online-med-directmail(.*)$ /online-master-of-education$1 [R=301]

RewriteRule ^online-bba-search(.*)$ /online-bba-management$1 [R=301]
RewriteRule ^online-bba-display(.*)$ /online-bba-management$1 [R=301]
RewriteRule ^online-bba-facebook(.*)$ /online-bba-management$1 [R=301]
RewriteRule ^online-bba-remarketing(.*)$ /online-bba-management$1 [R=301]
RewriteRule ^online-bba-directmail(.*)$ /online-bba-management$1 [R=301]

RewriteRule ^entry-dnap-search(.*)$ /entry-level-dnap$1 [R=301]
RewriteRule ^entry-dnap-display(.*)$ /entry-level-dnap$1 [R=301]
RewriteRule ^entry-dnap-youtube(.*)$ /entry-level-dnap$1 [R=301]
RewriteRule ^entry-dnap-facebook(.*)$ /entry-level-dnap$1 [R=301]
RewriteRule ^entry-dnap-remarketing(.*)$ /entry-level-dnap$1 [R=301]
RewriteRule ^entry-dnap-directmail(.*)$ /entry-level-dnap$1 [R=301]

RewriteRule ^edd-search(.*)$ /edd$1 [R=301]
RewriteRule ^edd-display(.*)$ /edd$1 [R=301]
RewriteRule ^edd-facebook(.*)$ /edd$1 [R=301]
RewriteRule ^edd-directmail(.*)$ /edd$1 [R=301]

RewriteRule ^phdmft-search(.*)$ /phdmft$1 [R=301]
RewriteRule ^phdmft-display(.*)$ /phdmft$1 [R=301]
RewriteRule ^phdmft-remarketing(.*)$ /phdmft$1 [R=301]



RewriteRule ^admissions/undergraduate/how-to-apply/freshman(.*) /admissions/undergraduate/freshman$1 [R=301]
RewriteRule ^admissions/undergraduate/how-to-apply/transfer(.*) /admissions/undergraduate/transfer$1 [R=301]
RewriteRule ^admissions/undergraduate/how-to-apply/dual-enrollment(.*) /admissions/undergraduate/special-programs/dual-enrollment$1 [R=301]
RewriteRule ^admissions/undergraduate/how-to-apply/early-college-high-school(.*) /admissions/undergraduate/special-programs/early-college-high-school$1 [R=301]
RewriteRule ^admissions/undergraduate/how-to-apply/summer-strivers(.*) /admissions/undergraduate/special-programs/summer-strivers$1 [R=301]
RewriteRule ^admissions/undergraduate/how-to-apply(/)?$ /admissions/undergraduate/freshman/ [R=301]

RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/biology/biology-faculty/benjamin-miller.*$ /search/?q=404 [R=404]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/biology/news-and-events/department-news/leading-alzheimers-concussion-scientists-featured-at-fwlsc-networking-event.*$ /search/?q=404 [R=404]

RewriteRule ^academics/student-services(.*)$ /academics/student-resources$1 [R=301]

RewriteRule ^academics/business-administration/master-of-business-administration/news--events/department-news/top-five-list/how-your-earning-potential-changes-when-you-earn-your-mba/[^?]*(\?.*) https://txwes.edu/academics/business-administration/master-of-business-administration/news-and-events/department-news/top-five-list/top-five-list-news-archive/how-your-earning-potential-changes-when-you-earn-your-mba/$1 [R=301]
RewriteRule ^academics/business-administration/news--events/department-news/student-success/thomas-h-law-scholarship-recipient-blends-golf-business-principles-for-success/[^?]*(\?.*) https://txwes.edu/academics/business-administration/master-of-business-administration/news-and-events/department-news/top-five-list/top-five-list-news-archive/5-powerhouse-entrepreneurs-who-earned-their-mba/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/news--events/department-news/top-five-list/benefits-of-getting-your-masters-in-marriage-and-family-therapy-at-a-small-school/[^?]*(\?*.*) https://txwes.edu/academics/school-of-education/graduate-counseling/news-and-events/department-news/top-five-list/top-five-list-news-archive/benefits-of-getting-your-masters-in-marriage-and-family-therapy-at-a-small-school/$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/master-of-education/news--events/department-news/top-five-list/how-your-students-will-benefit-when-you-earn-your-masters-degree-in-education/[^?]*(\?*.*) https://txwes.edu/academics/school-of-education/graduate-education/master-of-education/news-and-events/department-news/top-five-list/top-five-list-news-archive/how-your-students-will-benefit-when-you-earn-your-masters-degree-in-education/$1 [R=301]
RewriteRule ^academics/business-administration/master-of-business-administration/news--events/department-news/top-five-list/5-powerhouse-entrepreneurs-who-earned-their-mba/[^?]*(\?*.*) https://txwes.edu/academics/business-administration/master-of-business-administration/news-and-events/department-news/top-five-list/top-five-list-news-archive/5-powerhouse-entrepreneurs-who-earned-their-mba/$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/news--events/department-news/top-five-list/top-5-reasons-to-get-your-masters-in-school-counseling/[^?]*(\?*.*) https://txwes.edu/academics/school-of-education/graduate-counseling/news-and-events/department-news/top-five-list/top-five-list-news-archive/top-5-reasons-to-get-your-masters-in-school-counseling/$1 [R=301]
RewriteRule ^academics/gpna/news--events/department-news/are-you-tough-enough-for-nurse-anesthesia/[^?]*(\?*.*) https://txwes.edu/academics/gpna/news-and-events/department-news/are-you-tough-enough-for-nurse-anesthesia/$1 [R=301]
RewriteRule ^academics/gpna/news--events/department-news/nurse-anesthesia-pros-and-cons/[^?]*(\?*.*) https://txwes.edu/academics/gpna/news-and-events/department-news/nurse-anesthesia-pros-and-cons/$1 [R=301]
RewriteRule ^academics/business-administration/master-of-business-administration/news--events/department-news/top-five-list/how-your-earning-potential-changes-when-you-earn-your-mba/[^?]*(\?*.*) https://txwes.edu/academics/business-administration/master-of-business-administration/news-and-events/department-news/top-five-list/top-five-list-news-archive/how-your-earning-potential-changes-when-you-earn-your-mba/$1 [R=301]

RewriteRule ^media/twu/content-assets/images/alumni/give_now\.png$ /media/style/icon/give_now.png [R=301]
RewriteRule ^media/twu/content-assets/images/alumni/ways_to_give\.png$ /media/style/icon/ways_to_give.png [R=301]
RewriteRule ^media/twu/content-assets/images/alumni/giving_options\.png$ /media/style/icon/giving_options.png [R=301]
RewriteRule ^media/twu/content-assets/images/alumni/our_donors\.png$ /media/style/icon/our_donors.png [R=301]

RewriteRule ^(.*)admissions-pending(.*) /$1admissions$2 [R=301]
RewriteRule ^(.*)admissions-old(.*) /$1admissions$2 [R=301]

RewriteRule ^research/department-news/get-the-quick-facts-about-texas-wesleyans-spring-enrollment(.*)$ /research/department-news/get-the-quick-facts-about-texas-wesleyans-fall-enrollment/ [R=301]

RewriteRule ^admissions/undergraduate/how-to-apply/international-students(/)?$ /admissions/international-students/ [R=301]
RewriteRule ^admissions/undergraduate/how-to-apply/international-students/admission-requirements(/)?$ /admissions/international-students/admission-requirements/ [R=301]
RewriteRule ^admissions/undergraduate/how-to-apply/international-students/applying-for-a-us-student-visa(/)?$ /admissions/international-students/applying-for-a-us-student-visa/ [R=301]
RewriteRule ^admissions/undergraduate/how-to-apply/international-students/on-campus-intensive-english-program(/)?$ /admissions/international-students/on-campus-intensive-english-program/ [R=301]

RewriteRule ^admissions/my-award/verify-your-fafsa/(.*)$ /admissions/scholarships-and-aid/my-award/verify-your-fafsa/$1 [R=301]

RewriteRule ^academics/natural-and-social-sciences/student-advising-information/(.*)$ /academics/natural-and-social-sciences/advising/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/pre-health-science-program/(.*)$ /academics/natural-and-social-sciences/get-involved/pre-health-science-program/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/pre-professional-program/(.*)$ /academics/preprofessional/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/stem/(.*)$ /academics/natural-and-social-sciences/get-involved/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/contact-a-professor/(.*)$ /academics/natural-and-social-sciences/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/about-the-dean/(.*)$ /academics/natural-and-social-sciences/faculty--staff/ricardo-rodriguez/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/2017-summer-courses/(.*)$ /academics/natural-and-social-sciences/summer-courses/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/continuing-education-in-it-training/(.*)$ /academics/natural-and-social-sciences/get-involved/continuing-education-in-it-training/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/mathematics/eyh/(.*)$ /academics/natural-and-social-sciences/get-involved/eyh/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/mathematics/texprep/(.*)$ /academics/natural-and-social-sciences/get-involved/texprep/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/physics/(.*)$ /academics/natural-and-social-sciences/undergraduate-minors/physics/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/biology/health-science/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/biology/degree-plans/bs-in-health-science/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/biology/health-science/sample-degree-plans/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/biology/degree-plans/bs-in-health-science/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/biology/biology-faculty/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/biology/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/biology/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/biology/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/biology/students-get-involved/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/biology/get-involved/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/biology/student-research/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/biology/undergraduate-research$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/chemistry-and-biochemistry/about-the-program/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/chemistry-and-biochemistry/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/chemistry-and-biochemistry/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/chemistry-and-biochemistry/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/chemistry-and-biochemistry/faculty/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/chemistry-and-biochemistry/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/chemistry-and-biochemistry/department-alumni-update/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/chemistry-and-biochemistry/get-involved/alumni-update/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/chemistry-and-biochemistry/instrumentation/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/chemistry-and-biochemistry/undergraduate-research/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/chemistry-and-biochemistry/outreach/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/chemistry-and-biochemistry/get-involved/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/chemistry-and-biochemistry/get-involved/student-acs-affiliate/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/chemistry-and-biochemistry/get-involved/american-chemical-society/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/computer-science/about-the-program/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/computer-science/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/computer-science/faculty-/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/computer-science/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/computer-science/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/computer-science/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/computer-science/careers/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/computer-science/careers-in-computer-science/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/computer-science/students-get-involved/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/computer-science/get-involved/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/criminal-justice/about-the-program/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/criminal-justice/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/criminal-justice/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/criminal-justice/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/criminal-justice/faculty/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/criminal-justice/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/criminal-justice/getting-involved/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/criminal-justice/get-involved/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/about-the-program/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/secondary-certification/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/degree-plans/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/careers/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/careers-in-history/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/historyfaculty/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/historyfaculty/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/history-resources/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/get-involved/history-resources/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/pate-scholarship/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/get-involved/pate-scholarship/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/phi-alpha-theta/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/get-involved/phi-alpha-theta/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/history/program-newsletter/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/history/news-and-events/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/mathematics/about-the-program/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/mathematics/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/mathematics/faculty/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/mathematics/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/mathematics/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/mathematics/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/mathematics/students-get-involved/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/mathematics/get-involved/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/paralegal/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/paralegal/degree-plan/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/paralegal/careers/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/paralegal/careers-in-paralegal-studies/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/paralegal/paralegal-faculty/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/paralegal/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/political-science/requirements-for-majors-and-minors/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/political-science/degree-plans/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/political-science/about-the-program/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/political-science/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/political-science/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/political-science/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/political-science/faculty/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/political-science/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/psychology/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/psychology/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/psychology/careers/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/psychology/careers-in-psychology/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/psychology/getting-involved-/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/psychology/get-involved/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/sociology/about-the-program/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/sociology/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/sociology/course-descriptions/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/sociology/degree-plans/course-descriptions/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/sociology/faculty/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/sociology/faculty--staff/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/sociology/getting-involved/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/sociology/get-involved/$1 [R=301]
RewriteRule ^academics/natural-and-social-sciences/undergraduate-programs/sociology/getting-involved/social-justice-club/(.*)$ /academics/natural-and-social-sciences/undergraduate-majors/sociology/get-involved/social-justice-league/$1 [R=301]

RewriteRule ^admissions/graduate/business(.*)$ /admissions/graduate/online-mba$1 [R=301]

RewriteRule ^academics/registrar/attendance-policies(.*)$ /academics/registrar/policies/attendance-policy$1 [R=301]
RewriteRule ^academics/registrar/registration-information(.*)$ /academics/registrar/register-for-class$1 [R=301]

RewriteRule ^academics/business-administration/meetadvisor/$ /academics/business-administration/advising/ [R=301]
RewriteRule ^academics/business-administration/english-practice-partner-program-e3p/$ /academics/business-administration/get-involved/english-practice-partner-program-e3p/ [R=301]
RewriteRule ^academics/business-administration/small-business-workshop/$ /academics/business-administration/get-involved/small-business-workshop/ [R=301]
RewriteRule ^academics/business-administration/business-continuing-education/$ /academics/business-administration/get-involved/ [R=301]
RewriteRule ^academics/business-administration/aacsb-and-public-disclosure/$ /academics/business-administration/aacsb-accreditation--public-disclosure/ [R=301]
RewriteRule ^academics/business-administration/aacsb-accreditation/$ /academics/business-administration/aacsb-accreditation--public-disclosure/ [R=301]
RewriteRule ^academics/business-administration/accounting/careers-in-accounting/$ /academics/business-administration/undergraduate-majors/accounting/careers-in-accounting/ [R=301]
RewriteRule ^academics/business-administration/accounting/$ /academics/business-administration/undergraduate-majors/accounting/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/bonnie-quillin/$ /academics/business-administration/undergraduate-majors/accounting/faculty--staff/bonnie-quillin/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/tom-tolleson-phd-/$ /academics/business-administration/undergraduate-majors/accounting/faculty--staff/tom-tolleson/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/kimberly-j-webb-phd-cpa/$ /academics/business-administration/undergraduate-majors/accounting/faculty--staff/kimberly-j-webb/ [R=301]
RewriteRule ^academics/business-administration/general-business/careers-in-business-administration/$ /academics/business-administration/undergraduate-majors/general-business/careers-in-business/ [R=301]
RewriteRule ^academics/business-administration/general-business/$ /academics/business-administration/undergraduate-majors/general-business/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/thomas-j-bell-iii-phd-pmp-pmi-sp-psmi-cisa-crisc-mlv3/$ /academics/business-administration/undergraduate-majors/general-business/faculty--staff/thomas-j-bell/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/heida-reed-ph-d/$ /academics/business-administration/undergraduate-majors/general-business/faculty--staff/gokcen-ogruk/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/gokcen-ogruk-ph-d-/$ /academics/business-administration/undergraduate-majors/general-business/faculty--staff/heida-reed/ [R=301]
RewriteRule ^academics/business-administration/finance/$ /academics/business-administration/undergraduate-majors/finance/ [R=301]
RewriteRule ^academics/business-administration/finance/careers-in-finance/$ /academics/business-administration/undergraduate-majors/finance/careers-in-finance/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/shenxiong-wu-ph-d/$ /academics/business-administration/undergraduate-majors/finance/faculty--staff/shenxiong-wu/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/sinan-yildirim-ph-d-/$ /academics/business-administration/undergraduate-majors/finance/faculty--staff/sinan-yildirim/ [R=301]
RewriteRule ^academics/business-administration/defaultforensic/$ /academics/business-administration/undergraduate-majors/forensic-accounting/ [R=301]
RewriteRule ^academics/business-administration/management/careers-in-management/$ /academics/business-administration/undergraduate-majors/management/careers-in-management/ [R=301]
RewriteRule ^academics/business-administration/management/$ /academics/business-administration/undergraduate-majors/management/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/trisha-anderson-phd-pmp/$ /academics/business-administration/undergraduate-majors/management/faculty--staff/trisha-anderson/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/rod-erakovich-phd-/$ /academics/business-administration/undergraduate-majors/management/faculty--staff/rod-erakovich/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/tommy-nichols-phd-/$ /academics/business-administration/undergraduate-majors/management/faculty--staff/tommy-nichols/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/meghan-wright-ph-d/$ /academics/business-administration/undergraduate-majors/management/faculty--staff/meghan-wright/ [R=301]
RewriteRule ^academics/business-administration/marketing/careers-in-marketing/$ /academics/business-administration/undergraduate-majors/marketing/careers-in-marketing/ [R=301]
RewriteRule ^academics/business-administration/marketing/$ /academics/business-administration/undergraduate-majors/marketing/ [R=301]
RewriteRule ^academics/business-administration/faculty-and-staff/sua-jeon-ph-d/$ /academics/business-administration/undergraduate-majors/marketing/faculty--staff/sua-jeon-ph-d/ [R=301]
RewriteRule ^academics/business-administration/master-of-business-administration/$ /academics/business-administration/graduate-programs/mba/ [R=301]
RewriteRule ^academics/business-administration/online-mba/$ /academics/business-administration/graduate-programs/online-mba/ [R=301]

RewriteRule ^admissions/visit-campus/upcoming-events/campus-visit-plus(.*)$ /admissions/visit-campus/upcoming-events/senior-preview-day$1 [R=301]
RewriteRule ^admissions/visit-campus/upcoming-events/tcc-day(.*)$ /admissions/visit-campus/upcoming-events/tcc-preview-day$1 [R=301]
RewriteRule ^admissions/visit-campus/upcoming-events/transfer-day(.*)$ /admissions/visit-campus/upcoming-events/transfer-preview-day$1 [R=301]
RewriteRule ^admissions/visit-campus/my-visit-options/daily-campus-tour(.*)$ /admissions/visit-campus/daily-campus-tour$1 [R=301]

RewriteRule ^communications/project-requests(.*)$ /communications/request-a-project$1 [R=301]
RewriteRule ^communications/training-opportunities(.*)$ /communications/traing-with-us$1 [R=301]
RewriteRule ^communications/policies-and-procedures(.*)$ /communications/resources$1 [R=301]

RewriteRule ^brand(/)?$ /communications/resources/$1 [R=301]
RewriteRule ^brand/our-brand(.*)$ /communications/resources/our-brand$1 [R=301]
RewriteRule ^brand/our-values(.*)$ /communications/resources/our-brand$1 [R=301]
RewriteRule ^brand/see-the-campaign(.*)$ /communications/resources/our-brand$1 [R=301]
RewriteRule ^brand/brand-style-guide(.*)$ /communications/resources/our-brand$1 [R=301]
RewriteRule ^brand/brand-policies(.*)$ /communications/resources/our-brand$1 [R=301]
RewriteRule ^brand/resource-toolbox(.*)$ /communications/resources$1 [R=301]
RewriteRule ^brand/share-your-story(.*)$ /communications$1 [R=301]

RewriteRule ^communications/web/news-and-events(/)?$ /communications/news-and-events/ [R=301]
RewriteRule ^communications/web/news-and-events/all-news(/)?$ /communications/news-and-events/department-news/ [R=301]
RewriteRule ^communications/web/news-and-events/all-news/training-opportunities(.*)$ /communications/news-and-events/department-news/training-opportunities$1 [R=301]
RewriteRule ^communications/web/news-and-events/all-news/website-tips(.*)$ /communications/news-and-events/department-news/website-tips$1 [R=301]
RewriteRule ^communications/web/news-and-events/all-news/campus-buzz(.*)$ /communications/news-and-events/department-news/campus-buzz$1 [R=301]

RewriteRule ^communications/web/website-management(.*)$ /communications/traing-with-us$1 [R=301]
RewriteRule ^communications/web/update-and-approval-process(.*)$ /communications/resources$1 [R=301]
RewriteRule ^communications/web/web-training(.*)$ /communications/traing-with-us$1 [R=301]
RewriteRule ^communications/web/web-tips-and-downloads(.*)$ /communications/resources$1 [R=301]
RewriteRule ^communications/strategic-partnerships(.*)$	/academic-partnerships$1 [R=301]

RewriteRule ^academics/artsletters/student-advising-information-/$ /academics/artsletters/advising/ [R=301]
RewriteRule ^academics/artsletters/english/$ /academics/artsletters/english-and-foreign-language/ [R=301]
RewriteRule ^academics/artsletters/english/course-descriptions/$ /academics/artsletters/undergraduate-majors/english-and-foreign-language/degree-plans/course-descriptions/ [R=301]
RewriteRule ^academics/artsletters/english/concentrations-and-ceritifications/$ /academics/artsletters/undergraduate-majors/english-and-foreign-language/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/spanish/$ /academics/artsletters/english-and-foreign-language/ [R=301]
RewriteRule ^academics/artsletters/spanish/careers-in-spanish/$ /academics/artsletters/english-and-foreign-language/careers-in-english--foreign-language/ [R=301]
RewriteRule ^academics/artsletters/spanish/courses/$ /academics/artsletters/undergraduate-majors/english-and-foreign-language/degree-plans/course-descriptions/ [R=301]
RewriteRule ^academics/artsletters/spanish/news-and-events/$ /academics/artsletters/english--foreign-language/news-and-events/ [R=301]
RewriteRule ^academics/artsletters/liberal-studies/$ /academics/artsletters/undergraduate-majors/liberal-studies/ [R=301]
RewriteRule ^academics/artsletters/liberal-studies/degree-outlines/$ /academics/artsletters/undergraduate-majors/liberal-studies/degree-plan/ [R=301]
RewriteRule ^academics/artsletters/liberal-studies/news-and-events/$ /academics/artsletters/undergraduate-majors/liberal-studies/news-and-events/ [R=301]
RewriteRule ^academics/artsletters/mass-communication/$ /academics/artsletters/undergraduate-majors/mass-communication/ [R=301]
RewriteRule ^academics/artsletters/mass-communication/careers/$ /academics/artsletters/undergraduate-majors/mass-communication/careers-in-communication/ [R=301]
RewriteRule ^academics/artsletters/mass-communication/courses/$ /academics/artsletters/undergraduate-majors/mass-communication/degree-plans/course-descriptions/ [R=301]
RewriteRule ^academics/artsletters/mass-communication/faculty-and-staff/$ /academics/artsletters/undergraduate-majors/mass-communication/faculty-and-staff/ [R=301]
RewriteRule ^academics/artsletters/mass-communication/marjorie-herrera-lewis-speaker-series/$ /academics/artsletters/mass-communication/marjorie-herrera-lewis-endowed-speaker-series/ [R=301]
RewriteRule ^academics/artsletters/mass-communication/news-and-events/$ /academics/artsletters/mass-communication/news-and-events/ [R=301]
RewriteRule ^academics/artsletters/music/$ /academics/artsletters/undergraduate-majors/music/ [R=301]
RewriteRule ^academics/artsletters/music/prospective-students/$ /academics/artsletters/undergraduate-majors/music/music-resources/ [R=301]
RewriteRule ^academics/artsletters/music/current-students/$ /academics/artsletters/undergraduate-majors/music/get-involved/ [R=301]
RewriteRule ^academics/artsletters/music/bachelor-of-arts-in-music/$ /academics/artsletters/undergraduate-majors/music/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/music/bachelor-of-arts-in-music/degree-requirements/$ /academics/artsletters/undergraduate-majors/music/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/music/bachelor-of-arts-in-music/courses-of-study/$ /academics/artsletters/undergraduate-majors/music/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/music/bachelor-of-music-education/$ /academics/artsletters/undergraduate-majors/music/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/music/music-minor/$ /academics/artsletters/undergraduate-majors/music/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/music/special-events-and-competitions/$ /academics/artsletters/undergraduate-majors/music/special-events-and-competitions/ [R=301]
RewriteRule ^academics/artsletters/music/ensembles/$ /academics/artsletters/undergraduate-majors/music/get-involved/ [R=301]
RewriteRule ^academics/artsletters/music/faculty-and-staff/$ /academics/artsletters/undergraduate-majors/music/faculty-and-staff/ [R=301]
RewriteRule ^academics/artsletters/music/news-and-events/$ /academics/artsletters/undergraduate-majors/music/news-and-events/ [R=301]
RewriteRule ^academics/artsletters/music/fowm-chamber-series/$ /academics/artsletters/undergraduate-majors/music/special-events-and-competitions/ [R=301]
RewriteRule ^academics/artsletters/music/current-students/departmental-forms/$ /academics/artsletters/undergraduate-majors/music/music-resources/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/$ /academics/artsletters/undergraduate-majors/religion/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/christian-and-comparative-studies/$ /academics/artsletters/undergraduate-majors/religion/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/interdisciplinary-studies/$ /academics/artsletters/undergraduate-majors/religion/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/online-comparative-religious-studies/$ /academics/artsletters/undergraduate-majors/religion/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/online-comparative-religious-studies/the-degree-program/$ /academics/artsletters/undergraduate-majors/religion/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/online-comparative-religious-studies/degree-outline/$ /academics/artsletters/undergraduate-majors/religion/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/online-comparative-religious-studies/why-comparative-religious-studies/$ /academics/artsletters/undergraduate-majors/religion/degree-plans/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/course-descriptions/$ /academics/artsletters/undergraduate-majors/religion/degree-plans/religion--philosophy-course-descriptions/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/study-abroad/$ /academics/artsletters/undergraduate-majors/religion/get-involved/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/special-programs/$ /academics/artsletters/undergraduate-majors/religion/get-involved/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/faculty-and-staff/$ /academics/artsletters/undergraduate-majors/religion/faculty-and-staff/ [R=301]
RewriteRule ^academics/artsletters/religion-and-humanities/news-and-events/$ /academics/artsletters/undergraduate-majors/religion/news-and-events/ [R=301]
RewriteRule ^academics/artsletters/theatre/current-students/$ /academics/artsletters/undergraduate-majors/theatre/theatre-resources/ [R=301]
RewriteRule ^academics/artsletters/theatre/theatre-courses/$ /academics/artsletters/undergraduate-majors/theatre/degree-plans/course-descriptions/ [R=301]
RewriteRule ^academics/artsletters/theatre/photo-galleries/$ /academics/artsletters/undergraduate-majors/theatre/box-office/photo-gallery/ [R=301]
RewriteRule ^academics/artsletters/theatre/faculty-and-staff/$ /academics/artsletters/undergraduate-majors/theatre/faculty-and-staff/ [R=301]
RewriteRule ^academics/artsletters/theatre/program-advertising/$ /academics/artsletters/undergraduate-majors/theatre/box-office/program-advertising/ [R=301]
RewriteRule ^academics/artsletters/theatre/production-history/$ /academics/artsletters/undergraduate-majors/theatre/box-office/production-history/ [R=301]
RewriteRule ^academics/artsletters/theatre/$ /academics/artsletters/undergraduate-majors/theatre/box-office/ [R=301]

RewriteRule ^academics/school-of-education/graduate-counseling(/)?$ /academics/health-professions/graduate-programs/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/degree-programs(/)?$ /academics/health-professions/graduate-programs/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/student-resources(/)?$ /academics/health-professions/graduate-programs/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/news-and-events(/)?$ /academics/health-professions/news--events/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/student-resources(/)?$ /academics/health-professions/graduate-programs/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/doctoral-studies(/)?$ /academics/health-professions/graduate-programs/marriage--family-therapy/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/master-therapist-series(/)?$ /academics/health-professions/graduate-programs/marriage--family-therapy/get-involved/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/marriage--family-therapy(/)?$ /academics/health-professions/graduate-programs/marriage--family-therapy/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/professional-counseling(/)?$ /academics/health-professions/graduate-programs/professional-counseling/ [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/school-counseling(/)?$ /academics/health-professions/graduate-programs/school-counseling/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/application-instructions(/)?$ /admissions/graduate/nurse-anesthesia/msna/how-to-apply/application-instructions/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/admission-requirements(/)?$ /admissions/graduate/nurse-anesthesia/msna/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/priority-dates(/)?$ /admissions/graduate/nurse-anesthesia/msna/how-to-apply/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/distance-learning(/)?$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations(/)?$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/financial-aid(/)?$ /admissions/graduate/nurse-anesthesia/msna/what-will-it-cost/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/about-the-program(/)?$ /admissions/graduate/nurse-anesthesia/msna/how-long-will-it-take/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/your-clinical-experience(/)?$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/your-clinical-experience/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/how-do-i-start(/)?$ /admissions/graduate/nurse-anesthesia/msna/admitted-students/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/current-msna-students(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/news-and-events(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/ [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice(/)?$ /admissions/graduate/nurse-anesthesia/doctor-of-nurse-anesthesia-practice/ [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/application-instructions(/)?$ /admissions/graduate/nurse-anesthesia/doctor-of-nurse-anesthesia-practice/how-to-apply/ [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/about-the-program(/)?$ /admissions/graduate/nurse-anesthesia/doctor-of-nurse-anesthesia-practice/how-long-will-it-take/ [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/common-dnap-questions(/)?$ /admissions/graduate/nurse-anesthesia/doctor-of-nurse-anesthesia-practice/ [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/financial-aid(/)?$ /admissions/graduate/nurse-anesthesia/doctor-of-nurse-anesthesia-practice/what-will-it-cost/ [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/how-do-i-start(/)?$ /admissions/graduate/nurse-anesthesia/doctor-of-nurse-anesthesia-practice/admitted-students/ [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/news-and-events(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/ [R=301]
RewriteRule ^academics/gpna/program-statistics(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/program-statistics/ [R=301]
RewriteRule ^academics/gpna/faculty-and-staff(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/faculty-and-staff/ [R=301]
RewriteRule ^academics/gpna/faculty-and-staff/tito-tubog(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/faculty-and-staff/tito-tubog/ [R=301]
RewriteRule ^academics/gpna/faculty-and-staff/michele-ardigo(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/faculty-and-staff/michele-ardigo/ [R=301]
RewriteRule ^academics/gpna/faculty-and-staff/terri-kane(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/faculty-and-staff/terri-kane/ [R=301]
RewriteRule ^academics/gpna/faculty-and-staff/dion-gabaldon(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/faculty-and-staff/dion-gabaldon/ [R=301]
RewriteRule ^academics/gpna/faculty-and-staff/brian-koonce(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/faculty-and-staff/brian-koonce/ [R=301]
RewriteRule ^academics/gpna/accreditation(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/accreditation/ [R=301]
RewriteRule ^academics/gpna/news-and-events(/)?$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/ [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/alabama/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/arkansas/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/california/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/colorado/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/kansas/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/louisiana/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/north-dakota/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/ohio/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/master-of-science-in-nurse-anesthesia/site-locations/texas/(.*)$ /admissions/graduate/nurse-anesthesia/msna/distance-learning/find-my-site/$1 [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/news-and-events/department-news/(.*)$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/department-news/$1 [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/news-and-events/department-news/student-success/student-success-news-archive/(.*)$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/department-news/student-success/$1 [R=301]
RewriteRule ^academics/gpna/doctor-of-nurse-anesthesia-practice/news-and-events/department-news/professor-success/professor-success-news-archive/(.*)$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/department-news/professor-success/$1 [R=301]
RewriteRule ^academics/gpna/news-and-events/department-news/top-five-list/top-five-list-news-archive/(.*)$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/department-news/top-five-list/$1 [R=301]
RewriteRule ^academics/gpna/news-and-events/department-news/student-opportunities/student-opportunities-news-archive/(.*)$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/department-news/student-opportunities/$1 [R=301]
RewriteRule ^academics/gpna/news-and-events/department-news/community-outreach/community-outreach-news-archive/(.*)$ /academics/health-professions/graduate-programs/nurse-anesthesia/news-and-events/department-news/community-outreach/$1 [R=301]
RewriteRule ^cashier/online-mba-students/(.*)$ /cashier/online-programs/online-mba-students/$1 [R=301]
RewriteRule ^academics/registrar/register-for-class/online-mba-students/(.*)?$ /academics/registrar/register-for-class/online-students/$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-counseling/master-therapist-series(.*)?$ /academics/health-professions/graduate-programs/marriage--family-therapy/get-involved$1 [R=301]

RewriteRule ^student-life/student-handbook/title-ix-policy-prevention-and-response-to-gender-discrimination/$ /student-life/student-resources/student-handbook/title-ix-policy-prevention-and-response-to-gender-discrimination/ [R=301]
RewriteRule ^smarter/?$ /admissions/ [R=301]

RewriteRule ^admissions/graduate/nurse-anesthesia/doctor-of-nurse-anesthesia-practice(.*)$ /admissions/graduate/nurse-anesthesia/dnap$1 [R=301]

RewriteRule ^academics/school-of-education/undergraduate-education/undergraduate-education-programs(.*)$ /academics/school-of-education/undergraduate-majors/undergraduate-education/degree-plans$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-education/careersineducation(.*)$ /academics/school-of-education/undergraduate-majors/undergraduate-education/careers-in-education$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-education/student-teaching(.*)$ /academics/school-of-education/undergraduate-majors/undergraduate-education/teacher-certification$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-education/teacher-certification(.*)$ /academics/school-of-education/undergraduate-majors/undergraduate-education/teacher-certification$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-education/faculty(.*)$ /academics/school-of-education/undergraduate-majors/undergraduate-education/faculty-and-staff$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-education(.*)$ /academics/school-of-education/undergraduate-majors/undergraduate-eduction$1 [R=301]

RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/admissions-process(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training/apply-to-the-program$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/admission-criteria(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training/apply-to-the-program$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/retention-requirements(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training/apply-to-the-program$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/degree-plans(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training/degree-plan$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/degree-requirements(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training/degree-plan$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/scholarship-opportunities(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training/athletic-training-resources$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/boc-pass-rates(.*)$ /academics/school-of-education/undergraduate-majors/athletictraining/athletic-training-resources/boc-pass-rates$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/program-costs(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training/athletic-training-resources$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/infectious-disease-policy(.*)$ /academics/school-of-education/undergraduate-majors/athletictraining/athletic-training-resources/infectious-disease-policy$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining/news-and-events(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training/news-and-events$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/athletictraining(.*)$ /academics/school-of-education/undergraduate-majors/athletic-training$1 [R=301]

RewriteRule ^academics/school-of-education/undergraduate-kinesiology/exercise-science/degree-requirements(.*)$ /academics/school-of-education/undergraduate-majors/exercise-science/degree-plans$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/exercise-science/degree-plans(.*)$ /academics/school-of-education/undergraduate-majors/exercise-science/degree-plans$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/exercise-science(.*)$ /academics/school-of-education/undergraduate-majors/exercise-science$1 [R=301]

RewriteRule ^academics/school-of-education/undergraduate-kinesiology/minor-in-coaching(.*)$ /academics/school-of-education/undergraduate-majors/exercise-science/degree-plans$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/minor-in-exercise-science(.*)$ /academics/school-of-education/undergraduate-majors/exercise-science/degree-plans$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/minor-in-scuba(.*)$ /academics/school-of-education/undergraduate-majors/exercise-science/degree-plans$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/careersinkinesiology(.*)$ /academics/school-of-education/undergraduate-majors$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/faculty(.*)$ /academics/school-of-education/undergraduate-majors$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology/news-and-events(.*)$ /academics/school-of-education/undergraduate-majors$1 [R=301]
RewriteRule ^academics/school-of-education/undergraduate-kinesiology(.*)$ /academics/school-of-education/undergraduate-majors$1 [R=301]

RewriteRule ^academics/school-of-education/graduate-education/careersineducation(.*)$ /academics/school-of-education/graduate-programs/graduate-education$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/education-faculty(.*)$ /academics/school-of-education/graduate-programs/graduate-education$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/news-and-events(.*)$ /academics/school-of-education/graduate-programs/graduate-education$1 [R=301]

RewriteRule ^academics/school-of-education/graduate-education/master-of-education/fifth-year-option-program(.*)$ /academics/school-of-education/graduate-programs/graduate-education/degree-plans$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/master-of-education/graduation-information-(.*)$ /academics/school-of-education/graduate-programs/graduate-education/advising$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/master-of-education/summer-reading-clinic(.*)$ /academics/school-of-education/graduate-programs/graduate-education/get-involved/summer-reading-clinic$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/master-of-education/about-our-faculty/contact-information(.*)$ /academics/school-of-education/graduate-programs/graduate-education/faculty-and-staff$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/master-of-education/about-our-faculty(.*)$ /academics/school-of-education/graduate-programs/graduate-education/faculty-and-staff$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/master-of-education/news-and-events(.*)$ /academics/school-of-education/graduate-programs/graduate-education/news-and-events$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/master-of-education(.*)$ /academics/school-of-education/graduate-programs/graduate-education$1 [R=301]

RewriteRule ^academics/school-of-education/graduate-education/doctor-of-education/program-information(.*)$ /academics/school-of-education/graduate-programs$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/doctor-of-education/recent-dissertations-defended(.*)$ /academics/school-of-education/graduate-programs/graduate-education/get-involved/dissertations-defended$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/doctor-of-education/study-abroad-(.*)$ /academics/school-of-education/graduate-programs/graduate-education/get-involved$1 [R=301]
RewriteRule ^academics/school-of-education/graduate-education/doctor-of-education/professional-research-conference-(.*)$ /academics/school-of-education/graduate-programs/graduate-education/get-involved/southwest-education-research-association-conference$1 [R=301]



RewriteRule ^academics/school-of-education/graduate-education(.*) /academics/school-of-education/graduate-programs/graduate-education$1 [R=301]

RewriteRule ^cashier/tuition-and-fees/2017-2018-undergraduate-tuition--fees(.*) /cashier/tuition-and-fees/2017-18-undergraduate-tuition-and-fees$1 [R=301]
RewriteRule ^cashier/tuition-and-fees/2017-2018-graduate-tuition--fees(.*) /cashier/tuition-and-fees/2017-18-graduate-tuition-and-fees$1 [R=301]

RewriteRule ^alumni/news-and-events/all-news/stewardship/students-thank-donors-with-video-contest(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/students-thank-donors-with-video-contest$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/students-thank-university-donors-with-thank-you-video(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/students-thank-university-donors-with-thank-you-video$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/keep-your-eye-on-the-prize(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/keep-your-eye-on-the-prize$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/student-thanks-txwes-donors-with-original-video(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/student-thanks-txwes-donors-with-original-video$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/lady-rams-basketball-team-raises-funds-for-locker-room-renovation(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/lady-rams-basketball-team-raises-funds-for-locker-room-renovation$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/stewardship-news-archive-/join-us-for-the-2016-brick-dedication-ceremony(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/join-us-for-the-2016-brick-dedication-ceremony$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/txwes-students-can-compete-once-again-in-a-student-video-contest(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/txwes-students-can-compete-once-again-in-a-student-video-contest$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/be-a-part-of-our-season-support-the-lady-rams-softball-team(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/be-a-part-of-our-season-support-the-lady-rams-softball-team$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/stewardship-news-archive-/2017-texas-wesleyan-graduate-thanks-donors-with-an-original-song(.*) /alumni/news-and-events/all-news/your-gifts-at-work/your-gifts-at-work-news-archive/2017-texas-wesleyan-graduate-thanks-donors-with-an-original-song$1 [R=301]
RewriteRule ^alumni/news-and-events/all-news/stewardship/? /alumni/news-and-events/all-news/movers--shakers/ [R=410]
RewriteRule ^student-life/student-resources/career-services/careerlink(.*) /search/student-life/student-resources/career-services/careerlink/ [R=410]

<t4 type="navigation" id="298"/>

RewriteRule ^admissions/scholarships-and-aid(.*) /admissions/what-will-it-cost/scholarships-and-aid$1 [R=301]
RewriteRule ^admissions/what-will-it-cost/fees-costs-and-policies(.*) /admissions/what-will-it-cost/policies-and-consumer-information$1 [R=301]
