var summer_class_list = [
	{
		"term": "25-su61",
		"short_title": "acc analysis for deci making",
		"section_name": "acc-6210-20",
		"subject": "acc",
		"schools": "bus",
		"faculty_name": "kimberly webb",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su61",
		"short_title": "acc analysis for deci making",
		"section_name": "acc-6210-33",
		"subject": "acc",
		"schools": "bus",
		"faculty_name": "kimberly webb",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "acc analysis for deci making",
		"section_name": "acc-6210-34",
		"subject": "acc",
		"schools": "bus",
		"faculty_name": "kimberly webb",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "human patient simulation",
		"section_name": "ane-8101-01",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "brian cornelius",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su10",
		"short_title": "scholarly practice overview",
		"section_name": "ane-8120-01",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "tito tubog",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "w ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su10",
		"short_title": "doctoral scholarly work II",
		"section_name": "ane-8125-30",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "tito tubog",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "doctoral scholarly work II",
		"section_name": "ane-8125-31",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "terri kane",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "doctoral scholarly work II",
		"section_name": "ane-8125-32",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "angela mordecai",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "doctoral scholarly work II",
		"section_name": "ane-8125-33",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "scott shaffer",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "doctoral scholarly work II",
		"section_name": "ane-8125-34",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "bailey freeman",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "doctoral scholarly work II",
		"section_name": "ane-8125-35",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "brian cornelius",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "doctoral scholarly work II",
		"section_name": "ane-8125-36",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "jose castillo",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "doctoral scholarly work II",
		"section_name": "ane-8125-37",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "ashlee ericksen",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "info syst tech in hlthcare mgt",
		"section_name": "ane-8221-30",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "lisa taylor",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "clinical practicum b",
		"section_name": "ane-8222-01",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "scott shaffer",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "practicum"
	},
	{
		"term": "25-su10",
		"short_title": "advanced principles b",
		"section_name": "ane-8228-30",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "brian cornelius, angela mordecai",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "leadership for adv prac prof",
		"section_name": "ane-8265-01",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "jose castillo",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "w ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su10",
		"short_title": "advanced principles e",
		"section_name": "ane-8278-30",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "jose castillo, terri kane",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "evidence-based practice II",
		"section_name": "ane-8341-30",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "tito tubog",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "evidence-based practice II",
		"section_name": "ane-8341-31",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "ashlee ericksen",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su10",
		"short_title": "clinical practicum e",
		"section_name": "ane-8380-01",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "scott shaffer",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "",
		"instructional_method": "practicum"
	},
	{
		"term": "25-su10",
		"short_title": "principles anes practice i",
		"section_name": "ane-8509-01",
		"subject": "ane",
		"schools": "shp",
		"faculty_name": "ashlee ericksen, angela mordecai",
		"start_date": "06-02-2025",
		"end_date": "08-07-2025",
		"meeting_days": "m t th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su61",
		"short_title": "freshman online student exp",
		"section_name": "ase-1121-30",
		"subject": "ase",
		"schools": "gup",
		"faculty_name": "staff",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "college success & amer cult ex",
		"section_name": "ase-1311-01",
		"subject": "ase",
		"schools": "gup",
		"faculty_name": "staff",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "m th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su61",
		"short_title": "medical terminology",
		"section_name": "atr-2205-30",
		"subject": "atr",
		"schools": "edu",
		"faculty_name": "pamela rast",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "basic pharmacology",
		"section_name": "atr-3210-30",
		"subject": "atr",
		"schools": "edu",
		"faculty_name": "pamela rast",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "advance bus applica",
		"section_name": "bua-2310-31",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "adalheidur reed",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "international business",
		"section_name": "bua-3345-31",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "staff",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "bus analy for dec making",
		"section_name": "bua-4315-31",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "data visualization & analytics",
		"section_name": "bua-4317-31",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "bus analy for dec making",
		"section_name": "bua-6315-20",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su62",
		"short_title": "bus analy for dec making",
		"section_name": "bua-6315-33",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "bus analy for dec making",
		"section_name": "bua-6315-34",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "data visualization & analytics",
		"section_name": "bua-6317-20",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su61",
		"short_title": "data visualization & analytics",
		"section_name": "bua-6317-33",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "data visualization & analytics",
		"section_name": "bua-6317-34",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "manage info technol in bus",
		"section_name": "bua-6321-20",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "thomas bell",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su62",
		"short_title": "manage info technol in bus",
		"section_name": "bua-6321-33",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "thomas bell",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "manage info technol in bus",
		"section_name": "bua-6321-34",
		"subject": "bua",
		"schools": "bus",
		"faculty_name": "thomas bell",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "theories of counseling",
		"section_name": "cou-6301-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "misti sparks",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "multi-cross-cul coun",
		"section_name": "cou-6304-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "violeta kadieva",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "adv sexual & sex dys",
		"section_name": "cou-6305-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "russell bartee",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "res meth and prog eval",
		"section_name": "cou-6306-53",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "russell bartee",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "s",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "career dev & assess",
		"section_name": "cou-6307-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "staff",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "eth & prof cond for coun",
		"section_name": "cou-6309-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "richard bishop",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "marriage & fam coun",
		"section_name": "cou-6311-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "violeta kadieva",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "prof iden & preprac skills",
		"section_name": "cou-6314-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "violeta kadieva",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "men hlth clin prac i",
		"section_name": "cou-6315-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "kathleen wallace",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "men hlth clin prac i",
		"section_name": "cou-6315-40",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "kathleen wallace",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "m ",
		"instructional_method": "practicum"
	},
	{
		"term": "25-sue",
		"short_title": "prac in school counseling",
		"section_name": "cou-6319-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "kathleen wallace",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "prac in school counseling",
		"section_name": "cou-6319-40",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "kathleen wallace",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "m ",
		"instructional_method": "practicum"
	},
	{
		"term": "25-sue",
		"short_title": "family systems",
		"section_name": "cou-6322-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "richard bishop",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "family therapy practicum",
		"section_name": "cou-6324-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "misti sparks",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "family therapy practicum",
		"section_name": "cou-6324-40",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "misti sparks",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "th ",
		"instructional_method": "practicum"
	},
	{
		"term": "25-sue",
		"short_title": "psychopharmacology",
		"section_name": "cou-6331-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "michael ellison",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "crisis intervention counseling",
		"section_name": "cou-6332-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "russell bartee",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "sub abuse-addict disord",
		"section_name": "cou-6333-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "russell bartee",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "commun & clinic ment hlth adm",
		"section_name": "cou-6334-30",
		"subject": "cou",
		"schools": "shp",
		"faculty_name": "staff",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su1",
		"short_title": "special topics",
		"section_name": "crj-3399-01",
		"subject": "crj",
		"schools": "ans",
		"faculty_name": "staff",
		"start_date": "06-02-2025",
		"end_date": "07-03-2025",
		"meeting_days": "m t w th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su62",
		"short_title": "machine learning",
		"section_name": "csc-6320-33",
		"subject": "csc",
		"schools": "ans",
		"faculty_name": "william nash",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "computer graphics",
		"section_name": "csc-6351-33",
		"subject": "csc",
		"schools": "ans",
		"faculty_name": "atif mohammad",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "principles of economics i",
		"section_name": "eco-2305-31",
		"subject": "eco",
		"schools": "bus",
		"faculty_name": "gokcen ogruk-maz",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "fine arts elementary",
		"section_name": "edu-2208-30",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "solomon cross",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "technology for classroom instr",
		"section_name": "edu-3338-01",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "gwendolyn williams",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "m t w th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su61",
		"short_title": "foundations of bilingual ed",
		"section_name": "edu-3363-01",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "patsy robles-goodwin",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "m t w th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su61",
		"short_title": "envir process-assess for e c-6",
		"section_name": "edu-4340-01",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jessica salazar",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "m t w th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su62",
		"short_title": "school law admin",
		"section_name": "edu-6316-34",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "carrie redmond",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "principal practicum i",
		"section_name": "edu-6319-33",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jill balzer",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "principal practicum i",
		"section_name": "edu-6319-34",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jill balzer",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "principal practicum II",
		"section_name": "edu-6321-33",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jill balzer",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "principal practicum II",
		"section_name": "edu-6321-34",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jill balzer",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "addr soc-emo needs in urb edu",
		"section_name": "edu-6341-33",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "lisa dryden",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "sp popula & programs",
		"section_name": "edu-6342-33",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "elsa anderson",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "managing campus resources",
		"section_name": "edu-6348-33",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "carrie redmond",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "cross-cultural communications",
		"section_name": "edu-6357-34",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "lisa dryden",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "lead succ turn cult in urb edu",
		"section_name": "edu-6366-34",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "lisa dryden",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "policy-org change-educ",
		"section_name": "edu-8303-30",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jearl helvey",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "diversity frameworks",
		"section_name": "edu-8306-40",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "sandra mccoy-jackson",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "w ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "curriculum design",
		"section_name": "edu-8312-40",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "elsa anderson",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "w ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "emerging instruct strategies",
		"section_name": "edu-8313-40",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "lisa dryden",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "w ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "perspectives-leadership",
		"section_name": "edu-8320-40",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jearl helvey",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "w ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "supervision-psnl-instr pgm",
		"section_name": "edu-8323-40",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "april chiarelli",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "w ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "doctoral dissertation",
		"section_name": "edu-8331-03",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "lisa dryden",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "dissertation"
	},
	{
		"term": "25-sue",
		"short_title": "doctoral dissertation",
		"section_name": "edu-8331-04",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "elsa anderson",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "dissertation"
	},
	{
		"term": "25-sue",
		"short_title": "doctoral dissertation",
		"section_name": "edu-8331-05",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "sandra mccoy-jackson",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "dissertation"
	},
	{
		"term": "25-sue",
		"short_title": "doctoral dissertation",
		"section_name": "edu-8331-06",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "patsy robles-goodwin",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "dissertation"
	},
	{
		"term": "25-sue",
		"short_title": "doctoral dissertation",
		"section_name": "edu-8331-08",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jearl helvey",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "dissertation"
	},
	{
		"term": "25-sue",
		"short_title": "superintend & internship",
		"section_name": "edu-8335-40",
		"subject": "edu",
		"schools": "edu",
		"faculty_name": "jearl helvey",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "composition & grammar",
		"section_name": "eng-0300-01",
		"subject": "eng",
		"schools": "gup",
		"faculty_name": "carey hix",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "m th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su61",
		"short_title": "basic concepts of wellness",
		"section_name": "exs-1220-30",
		"subject": "exs",
		"schools": "edu",
		"faculty_name": "sharon carano",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su1",
		"short_title": "film aesthetics",
		"section_name": "far-1309-30",
		"subject": "far",
		"schools": "ans",
		"faculty_name": "staff",
		"start_date": "06-02-2025",
		"end_date": "07-03-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su1",
		"short_title": "digital photography",
		"section_name": "far-2322-01",
		"subject": "far",
		"schools": "ans",
		"faculty_name": "rolando palacio",
		"start_date": "06-02-2025",
		"end_date": "07-03-2025",
		"meeting_days": "m t w th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su2",
		"short_title": "digital photography",
		"section_name": "far-2322-01",
		"subject": "far",
		"schools": "ans",
		"faculty_name": "rolando palacio",
		"start_date": "07-09-2025",
		"end_date": "08-18-2025",
		"meeting_days": "m t w th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25-su62",
		"short_title": "corporate finance",
		"section_name": "fin-3313-31",
		"subject": "fin",
		"schools": "bus",
		"faculty_name": "shengxiong wu",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "financial management",
		"section_name": "fin-6215-20",
		"subject": "fin",
		"schools": "bus",
		"faculty_name": "sinan yildirim",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su61",
		"short_title": "financial management",
		"section_name": "fin-6215-33",
		"subject": "fin",
		"schools": "bus",
		"faculty_name": "sinan yildirim",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "financial management",
		"section_name": "fin-6215-34",
		"subject": "fin",
		"schools": "bus",
		"faculty_name": "sinan yildirim",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "research & evidence practice",
		"section_name": "fnp-6328-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "cheryl adair",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "family nurse practice i",
		"section_name": "fnp-6530-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "cheryl adair, kelly crawford",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "family nurse practitioner resi",
		"section_name": "fnp-6649-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "kelly crawford",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "applied statistics",
		"section_name": "fnp-8325-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "lisa taylor",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "research & evidence practice",
		"section_name": "fnp-8328-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "connie barker",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "advanced roles for dnp-fnp",
		"section_name": "fnp-8335-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "lisa taylor",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "dnp transition",
		"section_name": "fnp-8341-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "denise delarosa",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "dnp project",
		"section_name": "fnp-8360-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "family nurse practice i",
		"section_name": "fnp-8530-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "cheryl adair",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "family nurse practioner reside",
		"section_name": "fnp-8649-30",
		"subject": "fnp",
		"schools": "shp",
		"faculty_name": "kelly crawford",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "film and history",
		"section_name": "his-4346-30",
		"subject": "his",
		"schools": "ans",
		"faculty_name": "alistair maeer",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "the byzantines and turks",
		"section_name": "his-4348-20",
		"subject": "his",
		"schools": "ans",
		"faculty_name": "christopher ohan",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "m ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "comprehensive exam prep",
		"section_name": "mft-8118-40",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "misti sparks",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "on campus"
	},
	{
		"term": "25-sue",
		"short_title": "quant design, stat & analysis",
		"section_name": "mft-8304-40",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "vernesa perry",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "t ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "substance abuse in family",
		"section_name": "mft-8323-40",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "michael ellison",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "t ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "cur res-iss pro dev-eth mft",
		"section_name": "mft-8324-40",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "richard bishop",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "th ",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "dissertation defense",
		"section_name": "mft-8330-01",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "misti sparks",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "dissertation"
	},
	{
		"term": "25-sue",
		"short_title": "dissertation defense",
		"section_name": "mft-8330-02",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "linda metcalf",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "dissertation"
	},
	{
		"term": "25-sue",
		"short_title": "mft final master study",
		"section_name": "mft-8334-40",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "linda metcalf",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-sue",
		"short_title": "mft practicum i",
		"section_name": "mft-8414-40",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "misti sparks",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "w ",
		"instructional_method": "practicum"
	},
	{
		"term": "25-sue",
		"short_title": "mft practicum iv - tch & clin",
		"section_name": "mft-8417-40",
		"subject": "mft",
		"schools": "shp",
		"faculty_name": "staff",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "w ",
		"instructional_method": "practicum"
	},
	{
		"term": "25-su61",
		"short_title": "management theory & practice",
		"section_name": "mgt-3319-31",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "staff",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "production & operations mgt",
		"section_name": "mgt-3323-31",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "trisha anderson",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "special topics",
		"section_name": "mgt-3399-31",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "thomas bell",
		"start_date": "06-01-1996",
		"end_date": "10-02-2015",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "management leadership",
		"section_name": "mgt-4308-31",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "thomas nichols",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "quality management",
		"section_name": "mgt-4335-31",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "thomas bell",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "bus policy & decision making",
		"section_name": "mgt-4337-31",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "thomas nichols",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "procurement management",
		"section_name": "mgt-4345-31",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "trisha anderson",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "global perspectives in bus",
		"section_name": "mgt-6204-20",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "staff",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su62",
		"short_title": "global perspectives in bus",
		"section_name": "mgt-6204-33",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "staff",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "global perspectives in bus",
		"section_name": "mgt-6204-34",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "staff",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "strategic management",
		"section_name": "mgt-6207-33",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "junghoon song",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "strategic management",
		"section_name": "mgt-6207-34",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "junghoon song",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "organizational behavior",
		"section_name": "mgt-6209-20",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "staff",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su62",
		"short_title": "organizational behavior",
		"section_name": "mgt-6209-33",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "staff",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "organizational behavior",
		"section_name": "mgt-6209-34",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "staff",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "supply chain management",
		"section_name": "mgt-6311-20",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "trisha anderson",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su62",
		"short_title": "supply chain management",
		"section_name": "mgt-6311-33",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "trisha anderson",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "supply chain management",
		"section_name": "mgt-6311-34",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "trisha anderson",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "strategic management",
		"section_name": "mgt-6317-20",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "junghoon song",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su62",
		"short_title": "strategic management",
		"section_name": "mgt-6317-20",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "junghoon song",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su61",
		"short_title": "strategic management",
		"section_name": "mgt-6317-33",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "junghoon song",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "strategic management",
		"section_name": "mgt-6317-34",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "junghoon song",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "leadership",
		"section_name": "mgt-6318-20",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "thomas nichols",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su62",
		"short_title": "leadership",
		"section_name": "mgt-6318-33",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "thomas nichols",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su62",
		"short_title": "leadership",
		"section_name": "mgt-6318-34",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "thomas nichols",
		"start_date": "07-08-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "procurement mgmt",
		"section_name": "mgt-6345-20",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "trisha anderson",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su61",
		"short_title": "procurement mgmt",
		"section_name": "mgt-6345-33",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "trisha anderson",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "procurement mgmt",
		"section_name": "mgt-6345-34",
		"subject": "mgt",
		"schools": "bus",
		"faculty_name": "trisha anderson",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "integrated mktg management",
		"section_name": "mkt-6221-20",
		"subject": "mkt",
		"schools": "bus",
		"faculty_name": "sua jeon",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "hybrid"
	},
	{
		"term": "25-su61",
		"short_title": "integrated mktg management",
		"section_name": "mkt-6221-33",
		"subject": "mkt",
		"schools": "bus",
		"faculty_name": "sua jeon",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su61",
		"short_title": "integrated mktg management",
		"section_name": "mkt-6221-34",
		"subject": "mkt",
		"schools": "bus",
		"faculty_name": "sua jeon",
		"start_date": "05-27-2025",
		"end_date": "07-07-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "research for the dnp",
		"section_name": "nur-8328-30",
		"subject": "nur",
		"schools": "shp",
		"faculty_name": "connie barker",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "dnp transition",
		"section_name": "nur-8341-30",
		"subject": "nur",
		"schools": "shp",
		"faculty_name": "denise delarosa",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "dnp project",
		"section_name": "nur-8360-30",
		"subject": "nur",
		"schools": "shp",
		"faculty_name": "",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-sue",
		"short_title": "fam law & state",
		"section_name": "pls-3326-30",
		"subject": "pls",
		"schools": "ans",
		"faculty_name": "michelle payne",
		"start_date": "05-27-2025",
		"end_date": "08-18-2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25-su1",
		"short_title": "child psych",
		"section_name": "psy-3303-30",
		"subject": "psy",
		"schools": "ans",
		"faculty_name": "jay brown",
		"start_date": "06/02/2025",
		"end_date": "07/03/2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25/su2",
		"short_title": "adolescent development",
		"section_name": "psy-3305-30",
		"subject": "psy",
		"schools": "ans",
		"faculty_name": "matthew hand",
		"start_date": "07/09/2025",
		"end_date": "08/18/2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25/su1",
		"short_title": "abnormal psychology",
		"section_name": "psy-4375-30",
		"subject": "psy",
		"schools": "ans",
		"faculty_name": "matthew hand",
		"start_date": "06/02/2025",
		"end_date": "07/03/2025",
		"meeting_days": "",
		"instructional_method": "online"
	},
	{
		"term": "25/sue",
		"short_title": "reading techniques",
		"section_name": "rdg-0301-01",
		"subject": "rdg",
		"schools": "gup",
		"faculty_name": "laurie davis",
		"start_date": "05/27/2025",
		"end_date": "08/18/2025",
		"meeting_days": "m th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25/su62",
		"short_title": "children's biling literature",
		"section_name": "rdg-3328-01",
		"subject": "rdg",
		"schools": "edu",
		"faculty_name": "patsy robles-goodwin",
		"start_date": "07/08/2025",
		"end_date": "08/18/2025",
		"meeting_days": "m t w th ",
		"instructional_method": "on campus"
	},
	{
		"term": "25/sue",
		"short_title": "fund of speech",
		"section_name": "spc-1301-01",
		"subject": "spc",
		"schools": "ans",
		"faculty_name": "staff",
		"start_date": "05/27/2025",
		"end_date": "08/18/2025",
		"meeting_days": "m th ",
		"instructional_method": "on campus"
	}
];

export { summer_class_list };
