var participants = [
	{ "Position": "Staff Leader/Director", "First Name": "Kelly", "Last Name": "Anderson" },
	{ "Position": "Department Chair", "First Name": "Ilka", "Last Name": "Araujo" },
	 { "Position": "Faculty Member", "First Name": "Thomas", "Last Name": "Bell" },
	 { "Position": "Student  ", "First Name": "Alexandra", "Last Name": "Bennett" },
	 { "Position": "Vice President", "First Name": "Michele", "Last Name": "Boillotat" },
	 { "Position": "Associate Dean", "First Name": "Helena", "Last Name": "Bussell" },
	 { "Position": "Faculty Member", "First Name": "Stacia", "Last Name": "Campbell" },
	 { "Position": "Faculty Member", "First Name": "Sharon", "Last Name": "Carano" },
	 { "Position": "Staff Member", "First Name": "Jeri", "Last Name": "Chipman" },
	 { "Position": "General Counsel", "First Name": "Megan", "Last Name": "Cooley" },
	 { "Position": "Staff Leader/Director", "First Name": "Angela", "Last Name": "Dampeer" },
	 { "Position": "Student  ", "First Name": "Benji", "Last Name": "Domenzain" },
	 { "Position": "Athletics Director", "First Name": "Ricky", "Last Name": "Dotson" },
	 { "Position": "Student  ", "First Name": "Christine", "Last Name": "Duke" },
	 { "Position": "Staff Member", "First Name": "Robert", "Last Name": "Garza" },
	 { "Position": "Student  ", "First Name": "Orlanna", "Last Name": "Gooden" },
	 { "Position": "Vice President", "First Name": "Dennis", "Last Name": "Hall" },
	 { "Position": "Department Chair", "First Name": "Matt", "Last Name": "Hand" },
	 { "Position": "Department Chair", "First Name": "Ken", "Last Name": "Helvey" },
	 { "Position": "Faculty Member", "First Name": "Allen", "Last Name": "Henderson" },
	  { "Position": "Student Government Officer", "First Name": "Jordan", "Last Name": "Henthorn" },
	  { "Position": "Staff Member", "First Name": "Jason", "Last Name": "Hughes" },
	  { "Position": "Faculty Member", "First Name": "June", "Last Name": "Johnson" },
	  { "Position": "Staff", "First Name": "Tamika", "Last Name": "Johnson" },
	   { "Position": "Department Chair", "First Name": "Terri", "Last Name": "Kane" },
	   { "Position": "Staff member", "First Name": "Terence", "Last Name": "Kennedy" },
	   { "Position": "Board Officer", "First Name": "Glenn", "Last Name": "Lewis" },
	    { "Position": "Student Government Officer", "First Name": "Shiaza", "Last Name": "Liaqat" },
		{ "Position": "Vice President", "First Name": "Alan", "Last Name": "Liebrecht" },
		{ "Position": "Dean", "First Name": "Carlos", "Last Name": "Martinez" },
		 { "Position": "Staff Member", "First Name": "Ines", "Last Name": "Medrano" },
		 { "Position": "President", "First Name": "Emily", "Last Name": "Messer" },
		 { "Position": "Staff Member", "First Name": "Johntay", "Last Name": "Mooney" },
		 { "Position": "Staff Counsel Co-Chair", "First Name": "Jennifer", "Last Name": "Murphy" },
		 { "Position": "Vice President", "First Name": "Donna", "Last Name": "Nance" },
		  { "Position": "Associate Dean", "First Name": "Tommy", "Last Name": "Nichols" },
		   { "Position": "Associate Dean", "First Name": "Chris", "Last Name": "Ohan" },
		    { "Position": "Student  ", "First Name": "Cameron", "Last Name": "Pike" },
			 { "Position": "Provost", "First Name": "Hector", "Last Name": "Quintanilla" },
			 { "Position": "Staff Member", "First Name": "Angela", "Last Name": "Rainey" },
			 { "Position": "Faculty Chair", "First Name": "Pam", "Last Name": "Rast" },
			 { "Position": "Staff", "First Name": "Brian", "Last Name": "Renteria" },
			 { "Position": "Staff Member", "First Name": "Ekaterina", "Last Name": "Royston Anderson" },
			 { "Position": "Staff Member", "First Name": "Emily", "Last Name": "Snow" },
			  { "Position": "Staff Member", "First Name": "Gary", "Last Name": "Stout" },
			  { "Position": "Staff Counsel Co-Chair", "First Name": "Tammy", "Last Name": "Titlow" },
			  { "Position": "Faculty Member", "First Name": "Tito", "Last Name": "Tubog" },
			  { "Position": "Dean", "First Name": "Sameer", "Last Name": "Vaidya" },
			  { "Position": "Staff Member", "First Name": "Letty", "Last Name": "Vasquez" },
			  { "Position": "Staff", "First Name": "Brian", "Last Name": "Wanamaker" },
			  { "Position": "Faculty Member", "First Name": "Kimberly", "Last Name": "Webb" },
			   { "Position": "Staff", "First Name": "Djuana", "Last Name": "Young" }];

			   export var participants;
